api_version = "2024-04"
uid = "49a73b53-4a03-d95a-1997-bd0df6493da3a7cb16cb"

[[extensions]]
name = "Hat Designer Block"
handle = "hat-designer-block"
type = "theme"

[extensions.settings]
[[extensions.settings.fields]]
key = "api_base_url"
type = "text"
name = "API Backend URL (App Proxy)"
default = "/apps/caper-designer/api"
